<?php

use Illuminate\Database\Seeder;
use App\Seeder\BaseSeeder;
use App\Models\Builder;
use Carbon\Carbon;

class AddNewDataBuilderSeeder extends BaseSeeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $builders = [
                        [
                            'builder_id'           => '27',
                            'builer_mei'           => '（株）ウィズ・ワン',
                            'builer_mei_kana'      => 'ウィズワン',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1070062',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '港区南青山',
                            'tyoumei'              => '5丁目16番14号 ',
                            'tat_mei'              => 'モン・ブルービル2F',
                            'builer_busyo_mei'     => '本部（三上専務）',
                            'builer_mail'          => 'kmikami@with1.co.jp',
                            'builer_tel'           => '0354685141',
                            'builer_fax'           => '0354685143',
                            'builder_url'          => 'https://www.with1.co.jp/',
                            'eigyo_area_kbn'       => '00000000001111000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => '0910188',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '2',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '28',
                            'builer_mei'           => "（株）One'sLifeホーム",
                            'builer_mei_kana'      => 'ワンズライフホーム',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1540004',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '世田谷区太子堂',
                            'tyoumei'              => '4丁目1番1号',
                            'tat_mei'              => 'キャロットタワー14F',
                            'builer_busyo_mei'     => '樽見部長',
                            'builer_mail'          => 'tarumi@oneslife-home.com',
                            'builer_tel'           => '0357797622',
                            'builer_fax'           => '0357797644',
                            'builder_url'          => 'http://www.oneslife-home.com/',
                            'eigyo_area_kbn'       => '00000000000011000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => '0876381',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '8',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '29',
                            'builer_mei'           => '（株）みらいテクノハウス',
                            'builer_mei_kana'      => 'ミライテクノハウス',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1680072',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '杉並区高井戸東',
                            'tyoumei'              => '4丁目1番3号',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '大友部長',
                            'builer_mail'          => 'ootomo@mirai-t.co.jp',
                            'builer_tel'           => '0353367005',
                            'builer_fax'           => '0353367006',
                            'builder_url'          => 'http://www.mirai-t.co.jp/',
                            'eigyo_area_kbn'       => '00000000000010000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => 'N04374',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '7',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '30',
                            'builer_mei'           => '（株）バウハウス',
                            'builer_mei_kana'      => 'バウハウス',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1570062',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '世田谷区南烏山',
                            'tyoumei'              => '5丁目20番9号',
                            'tat_mei'              => 'ハウス・アム・バンホフ 1F　',
                            'builer_busyo_mei'     => '田中社長',
                            'builer_mail'          => 'tanaka@bau-aa.jp',
                            'builer_tel'           => '0353131811',
                            'builer_fax'           => '0353131812',
                            'builder_url'          => 'http://bau-aa.jp/about/',
                            'eigyo_area_kbn'       => '00000000000011000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => '0884563',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '6',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '31',
                            'builer_mei'           => '（株）アセットフォー',
                            'builer_mei_kana'      => 'アセットフォー',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1790081',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '練馬区北町',
                            'tyoumei'              => '2丁目13番11号 ',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '荒井社長',
                            'builer_mail'          => 'arai@assetfor.co.jp',
                            'builer_tel'           => '0335501311 ',
                            'builer_fax'           => '0335504987',
                            'builder_url'          => 'http://www.assetfor.co.jp/',
                            'eigyo_area_kbn'       => '00000000000010000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => 'N02633',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '1',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '32',
                            'builer_mei'           => '（株）西洋ハウジング',
                            'builer_mei_kana'      => 'セイヨウハウジング',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1700013',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '豊島区東池袋',
                            'tyoumei'              => '3丁目20番3号',
                            'tat_mei'              => '東池袋SSビル４F',
                            'builer_busyo_mei'     => '古牧支店長',
                            'builer_mail'          => 'furumaki.hitoshi@seiyo.co.jp',
                            'builer_tel'           => '0339842121',
                            'builer_fax'           => '0339842784',
                            'builder_url'          => 'http://www.seiyo.co.jp/',
                            'eigyo_area_kbn'       => '00010000001010000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => '0813553',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '3',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '33',
                            'builer_mei'           => '（株）谷川建設東京支店',
                            'builer_mei_kana'      => 'タニガワケンセツトウキョウシテン',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1540012',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '世田谷区駒沢',
                            'tyoumei'              => '3丁目16番13号',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '貝出本部長',
                            'builer_mail'          => 'kazzkaide0511@gmail.com',
                            'builer_tel'           => '0354867781',
                            'builer_fax'           => '0354866631',
                            'builder_url'          => 'https://www.tg-d.com/company/outline.html',
                            'eigyo_area_kbn'       => '00000000000011000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => '1512948',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '4',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '34',
                            'builer_mei'           => '（株）土屋ホーム',
                            'builer_mei_kana'      => 'ツチヤホーム',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '0600809',
                            'todouhuken_mei'       => '北海道',
                            'sikutyouson_mei'      => '札幌市北区北九条',
                            'tyoumei'              => '西三丁目七番地',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '北海道住宅事業部 北海道本店 技術部',
                            'builer_mail'          => 'nakagawa.m@tsuchiya.co.jp',
                            'builer_tel'           => '0117463930',
                            'builer_fax'           => '0117176452',
                            'builder_url'          => 'http://www.tsuchiyahome.jp/',
                            'eigyo_area_kbn'       => '11111111111111010011001010000000000000000000000',
                            'taiou_kbn'            => '010001',
                            'bdb_cd'               => '0487535',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '2',
                            'benefit_flg'          => '011',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '35',
                            'builer_mei'           => '（株）ハウセット',
                            'builer_mei_kana'      => 'ハウセット',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1300002',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '墨田区業平',
                            'tyoumei'              => '4丁目9番3号',
                            'tat_mei'              => 'ハウセット本社ビル7F',
                            'builer_busyo_mei'     => '事業開発部',
                            'builer_mail'          => 'y-takahashi@housset.co.jp',
                            'builer_tel'           => '0336219795',
                            'builer_fax'           => '0336219796',
                            'builder_url'          => 'http://www.housset.co.jp',
                            'eigyo_area_kbn'       => '00000000000110000000000000000000000000000000000',
                            'taiou_kbn'            => '000000',
                            'bdb_cd'               => '0911114',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '5',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '36',
                            'builer_mei'           => '桂建設（株）',
                            'builer_mei_kana'      => 'カツラケンセツ',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '3792311 ',
                            'todouhuken_mei'       => '群馬県',
                            'sikutyouson_mei'      => 'みどり市笠懸町阿左美',
                            'tyoumei'              => '７６３－２',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '桂建設本社',
                            'builer_mail'          => 'kats10@katsura-build.jp',
                            'builer_tel'           => '0277767723',
                            'builer_fax'           => '0277768547',
                            'builder_url'          => 'http://www.katsura-build.jp/',
                            'eigyo_area_kbn'       => '00000000010000000000000000000000000000000000000',
                            'taiou_kbn'            => '000000',
                            'bdb_cd'               => 'K06095',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '1',
                            'benefit_flg'          => '111',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '37',
                            'builer_mei'           => '（株）大成ホーム',
                            'builer_mei_kana'      => 'タイセイホーム',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '9012131',
                            'todouhuken_mei'       => '沖縄県',
                            'sikutyouson_mei'      => '浦添市',
                            'tyoumei'              => '牧港3-39-11',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '本社',
                            'builer_mail'          => 'keishu-k@taiseihome.jp',
                            'builer_tel'           => '0988777756',
                            'builer_fax'           => '0988771066',
                            'builder_url'          => 'http:www.taiseihome.jp/smt/index.html',
                            'eigyo_area_kbn'       => '00000000000000000000000000000000000000000000001',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => '24490',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '1',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '38',
                            'builer_mei'           => '三菱地所レジデンス（株）',
                            'builer_mei_kana'      => 'ミツビシジショレジデンス',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1008189',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '千代田区大手町',
                            'tyoumei'              => '一丁目6番１号',
                            'tat_mei'              => '大手町ビル',
                            'builer_busyo_mei'     => '広域営業部　法人営業グループ',
                            'builer_mail'          => 'shouji_tada@mec-r.com',
                            'builer_tel'           => '0332877296',
                            'builer_fax'           => '0332877143',
                            'builder_url'          => 'http://teikei.mec-r.com',
                            'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111111',
                            'taiou_kbn'            => '000010',
                            'bdb_cd'               => '',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '9',
                            'benefit_flg'          => '001',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '39',
                            'builer_mei'           => '野村不動産（株）',
                            'builer_mei_kana'      => 'ノムラフドウサン',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1630566',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '新宿区西新宿',
                            'tyoumei'              => '1丁目26番2号',
                            'tat_mei'              => '新宿野村ビル',
                            'builer_busyo_mei'     => '住宅事業本部営業推進部 営業推進課 提携法人担当',
                            'builer_mail'          => 'teikei@nomura-re.co.jp',
                            'builer_tel'           => '0333488758',
                            'builer_fax'           => '0120837600',
                            'builder_url'          => 'https://www.proud-web.jp/?utm_source=Yahoo%21SS&utm_medium=ppc&utm_campaign=proud-web',
                            'eigyo_area_kbn'       => '00000000001111000000000000000000000000000000000',
                            'taiou_kbn'            => '000010',
                            'bdb_cd'               => '',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '10',
                            'benefit_flg'          => '001',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '40',
                            'builer_mei'           => '東急不動産（株）',
                            'builer_mei_kana'      => 'トウキュウフドウサン',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1070062',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '港区南青山',
                            'tyoumei'              => '2丁目6番21号',
                            'tat_mei'              => 'TK南青山ビル',
                            'builer_busyo_mei'     => '住宅事業ユニット 販売統括部 販売管理グループ',
                            'builer_mail'          => 'Tomoko_Kikuchi@tokyu-land.co.jp',
                            'builer_tel'           => '05034823023',
                            'builer_fax'           => '0354141622',
                            'builder_url'          => 'http://sumai.tokyu-land.co.jp/alliance/index',
                            'eigyo_area_kbn'       => '10010000001111110000111111111100000000000000000',
                            'taiou_kbn'            => '000010',
                            'bdb_cd'               => '',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '11',
                            'benefit_flg'          => '001',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '41',
                            'builer_mei'           => 'セコムホームライフ（株）',
                            'builer_mei_kana'      => 'セコムホームライフ',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1510051',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '渋谷区千駄ヶ谷',
                            'tyoumei'              => '4丁目19番12号',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '営業本部 法人営業部',
                            'builer_mail'          => 'no-sudo@secom.co.jp',
                            'builer_tel'           => '0334787753',
                            'builer_fax'           => '0334787757',
                            'builder_url'          => 'http://www.secom-shl.co.jp/mansion/',
                            'eigyo_area_kbn'       => '00010001111111000000000000000000000000000000000',
                            'taiou_kbn'            => '000010',
                            'bdb_cd'               => '',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '15',
                            'benefit_flg'          => '001',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '42',
                            'builer_mei'           => '（株）長谷工コーポレーション',
                            'builer_mei_kana'      => 'ハセコウコーポレーション',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1058507',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '港区芝',
                            'tyoumei'              => '2丁目32番1号',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '法人営業部',
                            'builer_mail'          => '',
                            'builer_tel'           => '0120958909',
                            'builer_fax'           => '',
                            'builder_url'          => 'http://haseko-teikei.jp/hcxxx/',
                            'eigyo_area_kbn'       => '00010001111111000000001111111100000000010000001',
                            'taiou_kbn'            => '000010',
                            'bdb_cd'               => '',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '18',
                            'benefit_flg'          => '001',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '43',
                            'builer_mei'           => '菱重プロパティーズ（株）',
                            'builer_mei_kana'      => 'リョウジュウプロパティーズ',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '1080014',
                            'todouhuken_mei'       => '東京都',
                            'sikutyouson_mei'      => '港区芝',
                            'tyoumei'              => '5丁目34番6号',
                            'tat_mei'              => '新田町ビル４階',
                            'builer_busyo_mei'     => '不動産開発部 企画ｸﾞﾙｰﾌﾟ',
                            'builer_mail'          => 'houjin_kikaku@rjfp.mhi.co.jp',
                            'builer_tel'           => '0334511174',
                            'builer_fax'           => '0334511202',
                            'builder_url'          => 'https://www.jrwp.co.jp/',
                            'eigyo_area_kbn'       => '00000000001111000000111111111100000000010000000',
                            'taiou_kbn'            => '000010',
                            'bdb_cd'               => '',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '19',
                            'benefit_flg'          => '001',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '44',
                            'builer_mei'           => '（株）サンコーホーム',
                            'builer_mei_kana'      => 'サンコーホーム',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '0130064',
                            'todouhuken_mei'       => '秋田県',
                            'sikutyouson_mei'      => '横手市赤坂字舘ノ下',
                            'tyoumei'              => '155',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => 'マーケティング室',
                            'builer_mail'          => 'hashimoto@sanko-home.co.jp',
                            'builer_tel'           => '0182354779',
                            'builer_fax'           => '0182354778',
                            'builder_url'          => 'http://www.sanko-home.co.jp/',
                            'eigyo_area_kbn'       => '00001000000000000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => 'B02778',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '1',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '45',
                            'builer_mei'           => '（株）松美造園建設工業',
                            'builer_mei_kana'      => 'マツミゾウエンケンセツコウギョウ',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '0101413',
                            'todouhuken_mei'       => '秋田県',
                            'sikutyouson_mei'      => '秋田市御所野地蔵田',
                            'tyoumei'              => '2丁目2番2',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '営業部',
                            'builer_mail'          => 'naka_kikaku@matsuminoie.com',
                            'builer_tel'           => '0188398600',
                            'builer_fax'           => '0188398787',
                            'builder_url'          => 'http://www.matsuminoie.com/',
                            'eigyo_area_kbn'       => '00001000000000000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => 'B02106',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '2',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '46',
                            'builer_mei'           => '工藤建設（株）',
                            'builer_mei_kana'      => 'クドウケンセツ',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '2250003 ',
                            'todouhuken_mei'       => '神奈川県',
                            'sikutyouson_mei'      => '横浜市青葉区新石川',
                            'tyoumei'              => '四丁目33番地10',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '住宅事業部',
                            'builer_mail'          => 'yasuhiro_shimayama@kudo.co.jp',
                            'builer_tel'           => '0459115300',
                            'builer_fax'           => '0459113960',
                            'builder_url'          => 'http://www.kudo.co.jp/',
                            'eigyo_area_kbn'       => '00000000000011000000000000000000000000000000000',
                            'taiou_kbn'            => '010000',
                            'bdb_cd'               => 'N02595',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '2',
                            'display_order_2'      => '1',
                            'benefit_flg'          => '000',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        [
                            'builder_id'           => '47',
                            'builer_mei'           => '北海道セキスイハイム（株）',
                            'builer_mei_kana'      => 'ホッカイドウセキスイハイム',
                            'start_ymd'            => date('Y-m-d'),
                            'end_ymd'              => date('Y-m-d'),
                            'zip_no'               => '0010014',
                            'todouhuken_mei'       => '北海道',
                            'sikutyouson_mei'      => '札幌市北区北１４条',
                            'tyoumei'              => '西４丁目２－１',
                            'tat_mei'              => '',
                            'builer_busyo_mei'     => '札幌支店 資産活用・法人営業部 法人営業課',
                            'builer_mail'          => 'morimoto027@sekisui.com',
                            'builer_tel'           => '0117098520',
                            'builer_fax'           => '0117265816',
                            'builder_url'          => 'http://www.hokkaido-heim.com/',
                            'eigyo_area_kbn'       => '10000000000000000000000000000000000000000000001',
                            'taiou_kbn'            => '100000',
                            'bdb_cd'               => 'A03053',
                            'lcr_cd'               => '',
                            'mdm_houjin_cd'        => '',
                            'display_order_1'      => '1',
                            'display_order_2'      => '1',
                            'benefit_flg'          => '111',
                            'regis_ymd'            => date('Y-m-d'),
                            'upd_date'             => Carbon::now(),
                            'upd_user_id'          => 'y',
                            'upd_terminal_ip_addr' => 'y',
                            'patch_id'             => '',

                        ],
                        
                    ];
        
                    DB::beginTransaction();
                    try {
                            foreach ( $builders as $idx => $builder ) {

                            $isExits = Builder::where('builder_id',$builder['builder_id'])->first();
                            if( $isExits ) {
                                    continue;
                            }

                            $sub = Builder::create($builder);
                            }

                            $this->insertSeeder();
                            DB::commit();
                    } catch (\Exception $ex) {
                        DB::rollback();
                        throw $ex;
                    }
    }
}
