<?php

use Illuminate\Database\Seeder;
use App\Seeder\BaseSeeder;
use App\Models\Builder;
use Carbon\Carbon;

class BuilderSeeder extends BaseSeeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if ($this->checkSeeder('Builderv7Seeder')){
            return;
        }

        $builders = [
        	[
				'builder_id'           => '1',
				'builer_mei'           => 'ミサワホーム株式会社',
				'builer_mei_kana'      => 'ミサワホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1630833',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '新宿区西新宿',
				'tyoumei'              => '２丁目４番１号',
				'tat_mei'              => '新宿ＮＳビル１６Ｆ',
				'builer_busyo_mei'     => '法人営業部',
				'builer_mail'          => 'Takashi_Nishida@home.misawa.co.jp',
				'builer_tel'           => '333498044',
				'builer_fax'           => '345705668',
				'builder_url'          => 'http://www.misawa.co.jp/',
				'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111110',
				'taiou_kbn'            => '100010',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '17',
				'benefit_flg'          => '011',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '2',
				'builer_mei'           => '旭化成ホームズ株式会社',
				'builer_mei_kana'      => 'アサヒカセイホームズ',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1018101',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '千代田区神田神保町',
				'tyoumei'              => '1-105',
				'tat_mei'              => '神保町三井ビルディング３Ｆ',
				'builer_busyo_mei'     => '東京法人支店',
				'builer_mail'          => 'umehara.ab@om.asahi-kasei.co.jp',
				'builer_tel'           => '120102825',
				'builer_fax'           => '332963883',
				'builder_url'          => 'http://www.asahi-kasei.co.jp/hebel/support/index.html/',
				'eigyo_area_kbn'       => '00000001111111000010111111111100111000011000000',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '2',
				'benefit_flg'          => '111',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '3',
				'builer_mei'           => '株式会社アキュラホーム',
				'builer_mei_kana'      => 'アキュラホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1630234',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '新宿区西新宿',
				'tyoumei'              => '2丁目6番地1号',
				'tat_mei'              => '新宿住友ビル34F',
				'builer_busyo_mei'     => '営業推進課',
				'builer_mail'          => 'houjin@aqura.co.jp',
				'builer_tel'           => '0363025007',
				'builer_fax'           => '',
				'builder_url'          => 'http://www.aqura.co.jp/',
				'eigyo_area_kbn'       => '00000001101111000000011001110000010000000000000',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '1',
				'benefit_flg'          => '011',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '4',
				'builer_mei'           => 'サンヨーホームズ株式会社',
				'builer_mei_kana'      => 'サンヨーホームズ',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '5500005',
				'todouhuken_mei'       => '大阪府',
				'sikutyouson_mei'      => '大阪市西区西本町',
				'tyoumei'              => '１丁目４番１号',
				'tat_mei'              => 'オリックス本町ビル',
				'builer_busyo_mei'     => '経営戦略本部 事業推進部',
				'builer_mail'          => '',
				'builer_tel'           => '0665783407',
				'builer_fax'           => '0665783458',
				'builder_url'          => 'http://www.sanyohomes.co.jp/',
				'eigyo_area_kbn'       => '00000001111111000000111111111100000000011010000',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '3',
				'benefit_flg'          => '111',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
                'builder_id'           => '5',
                'builer_mei'           => '住友不動産株式会社（戸建）',
                'builer_mei_kana'      => 'スミトモフドウサン',
                'start_ymd'            => date('Y-m-d'),
                'end_ymd'              => date('Y-m-d'),
                'zip_no'               => '1630820',
                'todouhuken_mei'       => '東京都',
                'sikutyouson_mei'      => '新宿区西新宿',
                'tyoumei'              => '2-4-1',
                'tat_mei'              => '新宿ＮＳビル19Ｆ',
                'builer_busyo_mei'     => '総務部　営業推進チーム〔注文住宅・新築そっくりさん（リフォーム）〕',
                'builer_mail'          => 'soumu-eigyousuishin@sumitomo-rd.co.jp',
                'builer_tel'           => '0333461044',
                'builer_fax'           => '0333461491',
                'builder_url'          => 'http://www.j-urban.jp/?utm_source=yahoo&utm_medium=cpc',
                'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111110',
                'taiou_kbn'            => '100000',
                'bdb_cd'               => '',
                'lcr_cd'               => '',
                'mdm_houjin_cd'        => '',
                'display_order_1'      => '1',
                'display_order_2'      => '5',
                'benefit_flg'          => '011',
                'regis_ymd'            => date('Y-m-d'),
                'upd_date'             => Carbon::now(),
                'upd_user_id'          => 'y',
                'upd_terminal_ip_addr' => 'y',
                'patch_id'             => '',
            ],
            [
                'builder_id'           => '6',
                'builer_mei'           => '住友不動産株式会社 (マンション）',
                'builer_mei_kana'      => 'スミトモフドウサン',
                'start_ymd'            => date('Y-m-d'),
                'end_ymd'              => date('Y-m-d'),
                'zip_no'               => '1630820',
                'todouhuken_mei'       => '東京都',
                'sikutyouson_mei'      => '新宿区西新宿',
                'tyoumei'              => '2-4-1',
                'tat_mei'              => '新宿ＮＳビル19Ｆ',
                'builer_busyo_mei'     => '住宅分譲事業本部　提携法人担当〔分譲マンション・分譲戸建〕',
                'builer_mail'          => 'teikei-mansion@sumitomo-rd.co.jp',
                'builer_tel'           => '0333461044',
                'builer_fax'           => '0333461699',
                'builder_url'          => 'http://www.j-urban.jp/?utm_source=yahoo&utm_medium=cpc',
                'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111110',
                'taiou_kbn'            => '000010',
                'bdb_cd'               => '',
                'lcr_cd'               => '',
                'mdm_houjin_cd'        => '',
                'display_order_1'      => '1',
                'display_order_2'      => '5',
                'benefit_flg'          => '011',
                'regis_ymd'            => date('Y-m-d'),
                'upd_date'             => Carbon::now(),
                'upd_user_id'          => 'y',
                'upd_terminal_ip_addr' => 'y',
                'patch_id'             => '',
            ],
            [
                'builder_id'           => '7',
				'builer_mei'           => '住友林業株式会社',
				'builer_mei_kana'      => 'スミトモリンギョウ',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1710021',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '豊島区西池袋',
				'tyoumei'              => '1丁目11番1号',
				'tat_mei'              => 'メトロポリタンプラザビル15階',
				'builer_busyo_mei'     => '営業推進部 法人営業グループ',
				'builer_mail'          => 'takata_yumiko@star.sfc.co.jp',
				'builer_tel'           => '0359562160',
				'builer_fax'           => '0359563720',
				'builder_url'          => 'http://sfc.jp/ie/index.html',
				'eigyo_area_kbn'       => '10110111111111111111111111111111111111111111110',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '6',
				'benefit_flg'          => '001',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '8',
				'builer_mei'           => 'スウェーデンハウス株式会社',
				'builer_mei_kana'      => 'スウェーデンハウス',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1350061',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '江東区豊洲',
				'tyoumei'              => '６丁目１－９',
				'tat_mei'              => 'スマートハウジング豊洲まちなみ公園',
				'builer_busyo_mei'     => '営業企画グループ',
				'builer_mail'          => 'shhojin@swedenhouse.co.jp',
				'builer_tel'           => '0355475822',
				'builer_fax'           => '0355475823',
				'builder_url'          => 'www.swedenhouse.co.jp/cooperate/',
				'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111110',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '4',
				'benefit_flg'          => '001',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '9',
				'builer_mei'           => 'セキスイハイム',
				'builer_mei_kana'      => 'セキスイハイム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1058450',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '港区虎ノ門',
				'tyoumei'              => '2丁目3-17',
				'tat_mei'              => '虎ノ門2丁目タワー',
				'builer_busyo_mei'     => '未定',
				'builer_mail'          => '',
				'builer_tel'           => '',
				'builer_fax'           => '',
				'builder_url'          => '',
				'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111110',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '7',
				'benefit_flg'          => '111',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '10',
				'builer_mei'           => '積水ハウス株式会社',
				'builer_mei_kana'      => 'セキスイハウス',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '5310076',
				'todouhuken_mei'       => '大阪府',
				'sikutyouson_mei'      => '大阪市北区大淀中',
				'tyoumei'              => '１丁目１番８８号',
				'tat_mei'              => '梅田スカイビル',
				'builer_busyo_mei'     => '未定',
				'builer_mail'          => '',
				'builer_tel'           => '',
				'builer_fax'           => '',
				'builder_url'          => 'http://www.sekisuihouse.co.jp/?ad=ov',
				'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111110',
				'taiou_kbn'            => '10000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '8',
				'benefit_flg'          => '011',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '11',
				'builer_mei'           => '大和ハウス工業株式会社',
				'builer_mei_kana'      => 'ダイワハウスコウギョウ',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '5308241',
				'todouhuken_mei'       => '大阪府',
				'sikutyouson_mei'      => '大阪市北区梅田',
				'tyoumei'              => '３丁目３番５号',
				'tat_mei'              => '',
				'builer_busyo_mei'     => '営業本部　営業推進部大阪法人営業推進室',
				'builer_mail'          => ' koike03@daiwahouse.jp',
				'builer_tel'           => '0663421374',
				'builer_fax'           => '0663421577',
				'builder_url'          => 'http://www.daiwahouse.co.jp/',
				'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111111',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '11',
				'benefit_flg'          => '111',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '12',
				'builer_mei'           => 'タマホーム株式会社',
				'builer_mei_kana'      => 'タマホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1080074',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '港区高輪',
				'tyoumei'              => '3丁目22番9号',
				'tat_mei'              => '本社ビル',
				'builer_busyo_mei'     => '法人営業部',
				'builer_mail'          => '17000houjin@tamahome.jp',
				'builer_tel'           => '0364081260',
				'builer_fax'           => '0364081671',
				'builder_url'          => 'https://customer.tamahome.jp/alliance_p/',
				'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111111',
				'taiou_kbn'            => '100010',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '12',
				'benefit_flg'          => '011',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '13',
				'builer_mei'           => '大成建設ハウジング株式会社',
				'builer_mei_kana'      => 'タイセイケンセツハウジング',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1631019',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '新宿区西新宿',
				'tyoumei'              => '3丁目7‐1',
				'tat_mei'              => '新宿パークタワー19階',
				'builer_busyo_mei'     => '営業本部　第3法人営業部',
				'builer_mail'          => 'so-mym00@pub.taisei.co.jp',
				'builer_tel'           => '0353398085',
				'builer_fax'           => '0353232475',
				'builder_url'          => 'http://www.palcon.jp/',
				'eigyo_area_kbn'       => '10010001111111111111111111111100111010011111110',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '9',
				'benefit_flg'          => '111',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '14',
				'builer_mei'           => '大東建託株式会社',
				'builer_mei_kana'      => 'ダイトウケンタク',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1088211',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '港区港南',
				'tyoumei'              => '2丁目16番1号',
				'tat_mei'              => '',
				'builer_busyo_mei'     => '未定',
				'builer_mail'          => '',
				'builer_tel'           => '',
				'builer_fax'           => '',
				'builder_url'          => '',
				'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111111',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '10',
				'benefit_flg'          => '010',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '15',
				'builer_mei'           => 'トヨタホーム株式会社',
				'builer_mei_kana'      => 'トヨタホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '4610001',
				'todouhuken_mei'       => '愛知県',
				'sikutyouson_mei'      => '名古屋市東区泉',
				'tyoumei'              => '一丁目23番22号',
				'tat_mei'              => '栄本社ビル',
				'builer_busyo_mei'     => '法人営業部',
				'builer_mail'          => 'thsyokai@toyotahome.co.jp',
				'builer_tel'           => '0529524392',
				'builer_fax'           => '0529524575',
				'builder_url'          => 'https://www.toyotahome.co.jp/shokai/
',
				'eigyo_area_kbn'       => '01111111111111111111111111111111111111111111110',
				'taiou_kbn'            => '100010',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '13',
				'benefit_flg'          => '111',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '16',
				'builer_mei'           => '株式会社日本ハウスホールディングス',
				'builer_mei_kana'      => 'ニホンハウスホールディングス',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1020072',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '千代田区飯田橋',
				'tyoumei'              => '四丁目3番8号',
				'tat_mei'              => '日本ハウスHD飯田橋ビル',
				'builer_busyo_mei'     => '資材購買部',
				'builer_mail'          => 'tukai@nihonhouse-hd.co.jp',
				'builer_tel'           => '0352767350',
				'builer_fax'           => '0352767355',
				'builder_url'          => 'https://www.nihonhouse-hd.co.jp/philosophy/',
				'eigyo_area_kbn'       => '11111111111111111111111101111000110011011011110',
				'taiou_kbn'            => '100010',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '14',
				'benefit_flg'          => '11',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],

        	[
				'builder_id'           => '17',
				'builer_mei'           => 'パナホーム株式会社',
				'builer_mei_kana'      => 'パナホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '5608543',
				'todouhuken_mei'       => '大阪府',
				'sikutyouson_mei'      => '大阪府豊中市新千里西町',
				'tyoumei'              => '１丁目１番４号',
				'tat_mei'              => '',
				'builer_busyo_mei'     => '法人・特建開発推進部法人開発グループ',
				'builer_mail'          => 'k-yutani@nj.panahome.co.jp',
				'builer_tel'           => '0668343898',
				'builer_fax'           => '',
				'builder_url'          => 'http://www.panahome.jp/',
				'eigyo_area_kbn'       => '01110111111111111111111111111111111111111111111',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '15',
				'benefit_flg'          => '111',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],


        	[
				'builder_id'           => '18',
				'builer_mei'           => '古河林業株式会社',
				'builer_mei_kana'      => 'フルカワリンギョウ	',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '2200004',
				'todouhuken_mei'       => '神奈川県',
				'sikutyouson_mei'      => '横浜市西区北幸',
				'tyoumei'              => '2丁目9-30',
				'tat_mei'              => '加藤ビル４F',
				'builer_busyo_mei'     => '住宅事業本部',
				'builer_mail'          => 'y_takahashi@furukawa-ringyo.co.jp',
				'builer_tel'           => '0453283910',
				'builer_fax'           => '',
				'builder_url'          => '',
				'eigyo_area_kbn'       => '00000000101111000000000100000000000000000000000',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '16',
				'benefit_flg'          => '000',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],
			[
				'builder_id'           => '19',
				'builer_mei'           => '三井ホーム株式会社',
				'builer_mei_kana'      => 'ミツイホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1630543',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '新宿区西新宿',
				'tyoumei'              => '二丁目1番1号',
				'tat_mei'              => '新宿三井ビル53階',
				'builer_busyo_mei'     => '法人営業本部 法人営業推進部',
				'builer_mail'          => 't-nishida@mitsuihome.co.jp',
				'builer_tel'           => '0367585932',
				'builer_fax'           => '0367585934',
				'builder_url'          => 'http://www.mitsuihome-tokyo.com/intra2/index.php?com=lixil',
				'eigyo_area_kbn'       => '10110111111111111111111111111111111111111111110',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '18',
				'benefit_flg'          => '001',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],
        	[
				'builder_id'           => '20',
				'builer_mei'           => '三菱地所ホーム株式会社',
				'builer_mei_kana'      => 'ミツビシジショホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1070052',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '港区赤坂',
				'tyoumei'              => '2－14－27',
				'tat_mei'              => '国際新赤坂ビル東館',
				'builer_busyo_mei'     => '本店営業部',
				'builer_mail'          => 'hiroshi_tateno@mjhome.co.jp',
				'builer_tel'           => '0368878146',
				'builer_fax'           => '0368878149',
				'builder_url'          => 'http://www.mitsubishi-home.com/',
				'eigyo_area_kbn'       => '00000000001111000000000001111000000000000000000',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '19',
				'benefit_flg'          => '111',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],
        	[
				'builder_id'           => '21',
				'builer_mei'           => '株式会社ヤマダ・エスバイエルホーム',
				'builer_mei_kana'      => 'ヤマダエスバイエル',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '5320002',
				'todouhuken_mei'       => '大阪府',
				'sikutyouson_mei'      => '大阪市淀川区東三国',
				'tyoumei'              => '6丁目1番30　',
				'tat_mei'              => 'コボリマンション東三国2階',
				'builer_busyo_mei'     => '営業戦略本部　法人室',
				'builer_mail'          => 'n-korai@wm.sxl.co.jp',
				'builer_tel'           => '0663953424',
				'builer_fax'           => '0663953443',
				'builder_url'          => 'http://www.sxl.co.jp',
				'eigyo_area_kbn'       => '11101111111111011011111111111101100111111110110',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '20',
				'benefit_flg'          => '001',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],
        	[
				'builder_id'           => '22',
				'builer_mei'           => '株式会社レオハウス',
				'builer_mei_kana'      => 'レオハウス',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1630637',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '新宿区西新宿',
				'tyoumei'              => '1-25-1',
				'tat_mei'              => '新宿センタービル37階',
				'builer_busyo_mei'     => '商品室',
				'builer_mail'          => 'info@leohouse.jp',
				'builer_tel'           => '0333495211',
				'builer_fax'           => '0353397366',
				'builder_url'          => 'http://www.leohouse.jp/',
				'eigyo_area_kbn'       => '00110011111111011111111111111000110111111011110',
				'taiou_kbn'            => '100000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '1',
				'display_order_2'      => '21',
				'benefit_flg'          => '111',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],
        	[
				'builder_id'           => '23',
				'builer_mei'           => 'アイフルホーム',
				'builer_mei_kana'      => 'アイフルホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1360071',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '江東区亀戸',
				'tyoumei'              => '1-5-7',
				'tat_mei'              => '錦糸町ﾌﾟﾗｲﾑﾀﾜｰ',
				'builer_busyo_mei'     => 'ＦＣ販売促進部',
				'builer_mail'          => 'sato3.tanaka@lixil.com',
				'builer_tel'           => '0356268490',
				'builer_fax'           => '0356268316',
				'builder_url'          => 'http://www.eyefulhome.jp/',
				'eigyo_area_kbn'       => '11111111111111101111111111111011111111110111110',
				'taiou_kbn'            => '001000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '3',
				'display_order_2'      => '1',
				'benefit_flg'          => '011',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],
        	[
				'builder_id'           => '24',
				'builer_mei'           => 'フィアスホーム',
				'builer_mei_kana'      => 'フィアスホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1360071',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '江東区亀戸',
				'tyoumei'              => '1-5-7',
				'tat_mei'              => '錦糸町ﾌﾟﾗｲﾑﾀﾜｰ',
				'builer_busyo_mei'     => 'ＦＣ販売促進部',
				'builer_mail'          => 'sato3.tanaka@lixil.com',
				'builer_tel'           => '0356268490',
				'builer_fax'           => '0356268316',
				'builder_url'          => 'http://www.fiace.jp/',
				'eigyo_area_kbn'       => '00001101100011000111110011010000010111000000000',
				'taiou_kbn'            => '001000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '3',
				'display_order_2'      => '2',
				'benefit_flg'          => '011',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],
        	[
				'builder_id'           => '25',
				'builer_mei'           => 'ＧＬホーム',
				'builer_mei_kana'      => 'ジーエルホーム',
				'start_ymd'            => date('Y-m-d'),
				'end_ymd'              => date('Y-m-d'),
				'zip_no'               => '1360071',
				'todouhuken_mei'       => '東京都',
				'sikutyouson_mei'      => '江東区亀戸',
				'tyoumei'              => '1-5-7',
				'tat_mei'              => '錦糸町ﾌﾟﾗｲﾑﾀﾜｰ',
				'builer_busyo_mei'     => 'ＦＣ販売促進部',
				'builer_mail'          => 'kazunari.kunimoto@lixil.com',
				'builer_tel'           => '0356268490',
				'builer_fax'           => '0356268316',
				'builder_url'          => 'http://www.glhome.lixil-jk.co.jp/',
				'eigyo_area_kbn'       => '00110111011110000001111100100100000000000000000',
				'taiou_kbn'            => '001000',
				'bdb_cd'               => '',
				'lcr_cd'               => '',
				'mdm_houjin_cd'        => '',
				'display_order_1'      => '3',
				'display_order_2'      => '3',
				'benefit_flg'          => '011',
				'regis_ymd'            => date('Y-m-d'),
				'upd_date'             => Carbon::now(),
				'upd_user_id'          => 'y',
				'upd_terminal_ip_addr' => 'y',
				'patch_id'             => '',

        	],
            [
                'builder_id'           => '26',
                'builer_mei'           => 'スーパーウォール工法 取扱店',
                'builer_mei_kana'      => 'スーパーウォール',
                'start_ymd'            => date('Y-m-d'),
                'end_ymd'              => date('Y-m-d'),
                'zip_no'               => '1368535',
                'todouhuken_mei'       => '東京都',
                'sikutyouson_mei'      => '江東区大島',
                'tyoumei'              => '2-1-1',
                'tat_mei'              => '',
                'builer_busyo_mei'     => 'ZEH推進事業部 ZEH推進営業部 構造体営業G',
                'builer_mail'          => 'sw_jutakusyutoku@lixil.com',
                'builer_tel'           => '0336388157',
                'builer_fax'           => '0336388461',
                'builder_url'          => 'http://www.lixil.co.jp/lineup/construction_method/sw/',
                'eigyo_area_kbn'       => '11111111111111111111111111111111111111111111110',
                'taiou_kbn'            => '000100',
                'bdb_cd'               => '',
                'lcr_cd'               => '',
                'mdm_houjin_cd'        => '',
                'display_order_1'      => '4',
                'display_order_2'      => '1',
                'benefit_flg'          => '000',
                'regis_ymd'            => date('Y-m-d'),
                'upd_date'             => Carbon::now(),
                'upd_user_id'          => 'y',
                'upd_terminal_ip_addr' => 'y',
                'patch_id'             => '',
            ],
        ];

    	DB::beginTransaction();
        try {
            foreach ($builders as $key => $builder) {
                $builderDB = Builder::find($builder['builder_id']);
                if ($builder) {
                    $builderDB->builer_mei = $builder['builer_mei'];
                    $builderDB->builer_mei_kana = $builder['builer_mei_kana'];
                    $builderDB->start_ymd = $builder['start_ymd'];
                    $builderDB->end_ymd = $builder['end_ymd'];
                    $builderDB->zip_no = $builder['zip_no'];
                    $builderDB->todouhuken_mei = $builder['todouhuken_mei'];
                    $builderDB->sikutyouson_mei = $builder['sikutyouson_mei'];
                    $builderDB->tyoumei = $builder['tyoumei'];
                    $builderDB->tat_mei = $builder['tat_mei'];
                    $builderDB->builer_busyo_mei = $builder['builer_busyo_mei'];
                    $builderDB->builer_mail = $builder['builer_mail'];
                    $builderDB->builer_tel = $builder['builer_tel'];
                    $builderDB->builer_fax = $builder['builer_fax'];
                    $builderDB->builder_url = $builder['builder_url'];
                    $builderDB->eigyo_area_kbn = $builder['eigyo_area_kbn'];
                    $builderDB->taiou_kbn = $builder['taiou_kbn'];
                    $builderDB->bdb_cd = $builder['bdb_cd'];
                    $builderDB->lcr_cd = $builder['lcr_cd'];
                    $builderDB->mdm_houjin_cd = $builder['mdm_houjin_cd'];
                    $builderDB->display_order_1 = $builder['display_order_1'];
                    $builderDB->display_order_2 = $builder['display_order_2'];
                    $builderDB->benefit_flg = $builder['benefit_flg'];
                    $builderDB->regis_ymd = $builder['regis_ymd'];
                    $builderDB->upd_date = $builder['upd_date'];
                    $builderDB->upd_user_id = $builder['upd_user_id'];
                    $builderDB->upd_terminal_ip_addr = $builder['upd_terminal_ip_addr'];
                    $builderDB->patch_id = $builder['patch_id'];

                    $builderDB->save();
                } else {
                    $builder = Builder::create($builder);
                }
            }

            $this->insertSeeder();
            DB::commit();
        } catch (\Exception $ex) {
            DB::rollback();
            throw $ex;
        }
    }
}
