<?php

use Illuminate\Database\Seeder;
use App\Seeder\BaseSeeder;
use App\Models\Faq;
use Carbon\Carbon;

class FaqV2Seeder extends BaseSeeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        if ($this->checkSeeder()){
            return;
        }

         $faqs = [
            [
                'faskq_id'               => 'q1',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL Family STOREの会員登録を実施していないが、本登録を促すメールが届きました。どうしたら良いですか？',
                'ques_message'           => '恐れ入りますが、メールの内容をLIXIL Family STORE 事務局（lffs@lixil.com）へメールの内容を転送いただけますよう、お願いします。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],

            [
                'faskq_id'               => 'q2',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL Family STOREの会員に種類はありますか？',
                'ques_message'           => 'LIXIL会員：LIXILグループ（㈱LIXILグループを含む、(株)LIXILグループ及び同社の子会社、関連会社において業務委託先であり、個人又は法人に属する社員であり、かつLIXILグループ（㈱LIXILグループを含む、(株)LIXILグループ及び同社の子会社、関連会社の事業所内に席を持ち、且つLIXILが認めた方となります。
ファミリー会員：LIXIL会員の家族。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],

            [
                'faskq_id'               => 'q3',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL Family STOREはどの様な制度ですか？',
                'ques_message'           => '株式会社LIXILが運営する会員制の制度となります。制度には新築物件の購入を促進する『住宅購入・紹介』とリフォームを商品と工事付で提供する『リフォームストア』の個別に運営されるサービスとなります。詳細は専用WEBサイトをご参照ください。',
                'regis_date'            => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q4',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL会員がファミリー会員を招待する仕組みとなっていますが、LIXIL会員の招待をせずに、直接ファミリー会員になる事はできますか？',
                'ques_message'           => '申し訳ございませんが、LIXIL会員が招待をせずにファミリー会員となる事は出来ません。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q5',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL会員として、会員登録を完了させましたが、自分が指定するメールアドレスへ変更する事は出来ますか？',
                'ques_message'           => '申し訳ございませんが、LIXIL会員の方はメールアドレスの変更は出来ません。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q6',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL会員になりたいのですが、LIXILグループのメールアドレスを持っていません。どうしたらよろしいでしょうか。',
                'ques_message'           => '恐れ入りますが、原則としてメールアドレスの取得を実施いただけますよう、お願い致します。止むを得ない事情にてメールアドレスを取得できない場合は、身近にいるLIXILイントラへアクセスする事が可能な方より、『特別登録申請』を実施ください。万が一、メールアドレスの取得が可能な方が『特別登録申請』を実施いただいた場合は、『特別登録申請』をお断りさせていただく場合がございますので、予めご了承いただけますよう、お願い致します。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q7',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL会員になる為、必要な情報はありますか？',
                'ques_message'           => '①会員となられる方の個人情報
②LIXILグループ会社メールアドレス
③パスコードが必要となります。
詳細は株式会社LIXILのイントラをご参照ください。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q8',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL会員はどうしたらなれますか？',
                'ques_message'           => '株式会社LIXILのイントラサイトより、LIXIL Family STOREのTOP画面より会員登録画面へ進むことが出来ます。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q9',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'ファミリー会員として登録をしたいのですが、PCのメールアドレスを持っていません。どうしたらよいでしょうか。',
                'ques_message'           => 'お手数をお掛けし、大変申し訳ございませんがPCのメールアドレスを取得いただけますよう、お願い致します。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q10',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'ファミリー会員になる為、必要な情報はありますか？',
                'ques_message'           => '以下の３つの情報が必要となります
①LIXIL会員が招待コード発行機能で送付した招待コード
②会員となられる方の個人情報
③メールアドレス（PCのメールアドレス）',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q11',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'ファミリー会員はどうしたらなれますか？',
                'ques_message'           => 'LIXIL会員となった方より、ご家族の方をファミリー会員へ招待する事が出来ます。それ以外の方法がありません。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q12',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL Family STOREの会員登録は専用WEBサイト以外で登録可能ですか？',
                'ques_message'           => '申し訳ございませんが、原則専用WEBサイト以外では登録出来ません。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q13',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL Family STOREの会員登録画面でエラーが出て、会員の登録ができません。どうしたらいいですか？',
                'ques_message'           => '再度、「会社メールアドレス」と「パスコード」が正しいかのご確認をお願い致します。尚、会社メールアドレスのメールドメインが、パスコード確認時に表示されるもの以外は登録できませんので、メールドメインの確認も忘れずお願いします。又、LIXILグループ会社メールアドレス取得日の即日は登録できません。１日以上たってから、登録ください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q14',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXILグループの従業員ですが、社販制度を利用するのに、会員登録が必要ですか？',
                'ques_message'           => '会員登録が必要となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q15',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL会員の登録する際、LIXILグループの会社メールアドレス以外で、自ら指定してメールアドレスで登録したいのですが可能ですか？',
                'ques_message'           => '申し訳ございません。従業員の個人メールアドレスでの登録は出来ません。LIXILグループの会社メールアドレスのみでの登録となります。但し、ファミリー会員としてご家族の方を招待する場合、ご家族の方のメールアドレスは登録可能です。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q16',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => '会員登録する為の「パスコード」が分かりません。どうすれば調べることができますか？',
                'ques_message'           => 'LIXIL社内イントラのLIXIL Family STOREのページで確認することが出来ます。また「パスコード」はLIXILグループの会社毎に統一したコードとなっていますので、イントラを見れない方は、同じ会社の方でイントラを見れる方にお聞きしてください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q17',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => '家族が、LIXIL Family STOREの初期登録に必要な情報は何ですか？',
                'ques_message'           => 'LIXIL Family STOREに会員登録されたLIXIL従業員の方が、当サイト”リフォーム会員招待コード発行”機能にて家族の方を招待して下さい。招待する際の、「家族のメールアドレス」と「招待コード」となります。
尚、招待した家族の方は、LIXIL Family STORE リフォームのメニューのみ利用可能となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q18',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => '招待メールが家族に届きましたが、期限まで（１週間以内）に会員登録しなかった為、会員登録が出来なくなりました。どうすればいいですか？',
                'ques_message'           => '恐れ入りますが、LIXILグループ従業員の方が再度、招待して下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q19',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => '家族が、招待メールを削除してしまって、招待コードが分からなくなってしまった場合はどうしたらいいですか？',
                'ques_message'           => '申し訳ございません。LIXILグループ従業員の方が、再度、招待してください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q20',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => '招待以外で家族が直接LIXIL Family STOREの会員登録をする事は可能ですか？',
                'ques_message'           => '申し訳ございません。LIXILグループ従業員の招待を受けず、直接ご家族の方が登録を実施する事はできません。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q21',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => '本会員登録をする際、会社メールアドレスへ送付されたURLに期限まで（１週間以内）にアクセス出来なかったため、会員登録を完了できませんでした。どうすればいいですか？',
                'ques_message'           => '恐れ入りますが、再度、初期登録より実施をお願い致します。
',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q22',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => 'LIXIL Family STORE リフォームストアはLIXILトータルサービス請負を対象としていますが、何故、（株）LIXILトータルサービス以外の子会社は対象にならないのでしょうか？',
                'ques_message'           => '本制度を運用するにあたり、LIXILとして品質保証が出来、条件面等でのコントロール可能なグループ会社として、当面の間、（株）LIXILトータルサービスを指定工事会社と致しました。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q23',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '会員登録',
                'ask_message'            => '過去にLIXILG（LIXILG子会社、LIXIL、LIXIL子会社、LIXIL関連会社を含む）を退職している元従業員ですが、LIXIL会員もしくはファミリー会員になり、制度を利用することは可能ですか？',
                'ques_message'           => '申し訳ございません。元従業員の方は本制度の利用は出来ません。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q24',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => 'LIXIL Family STORE リフォームストアの元請工事する会社は自分で指定できますか？',
                'ques_message'           => 'LIXIL Family STORE リフォームストア工事会社を指定することはできません。元請工事は（株）LIXILトータルサービスとなります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q25',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => '現在、他社でLIXIL商品を採用したリフォームを商談中です。LIXIL Family STOREの制度を利用して、リフォーム工事は指定工事会社以外として、LIXIL商品のみを支給してもらうことはできますか？',
                'ques_message'           => '申し訳ございません、対象外です。（商品支給のみは出来ません）本制度は、LIXIL Family STOREの専用WEBサイトで申込みを行ったリフォーム案件のみが対象となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q26',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => '工事会社より提出された見積が思っていたよりも高いと感じます。商品の値引きをしてもらうのは可能でしょうか？',
                'ques_message'           => '今回はLIXIL Gの社販制度専用の価格設定をしていますので、商品の割引は不可となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],[
                'faskq_id'               => 'q27',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => '自宅近隣に（株）LIXILトータルサービスの直営ショップが無いのですが、本制度を利用する事は可能ですか？',
                'ques_message'           => '（株）LIXILトータルサービス直営ショップの未カバーエリアについては（株）LIXILトータルサービス各営業所販売課にて対応致します。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q28',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => 'トイレ以外にキッチン・風呂など他部位もRFしたいが、対応していただけるのですか？',
                'ques_message'           => '対象商品のリフォームに関しては可能です。対象商品以外のリフォームに対応できるは、（株）LIXILトータルサービスショップ営業部(lts10@lixil.com)へお問い合わせ下さい。但し、その場合社販対象商品以外は、適用対象外となります。ご了承ください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q29',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => 'リフォーム工事に立会は必要ですか？',
                'ques_message'           => 'リフォーム工事には必ず立会を実施いただきます。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q30',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => '自分の会社でもリフォーム工事が出来るのですが、（株）LIXILトータルサービスに依頼しなくていけないのですか？出来れば商品のみ購入したいと考えています。',
                'ques_message'           => '申し訳ございません。LIXIL Family STORE指定の工事業者のみの対応となります。（尚、商品のみの販売は対応しておりません。）',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q31',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => '自分でも工事が出来るのですが、（株）LIXILトータルサービスに依頼しなくていけないのですか？出来れば商品のみ購入したいと考えています。',
                'ques_message'           => '申し訳ございません。LIXIL Family STORE指定の工事業者のみの対応となります。（尚、商品のみの販売は対応しておりません。）',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q32',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => 'LIXIL Family STOREで購入できる商品は海外の物件でも取り付ける事は可能ですか？',
                'ques_message'           => '本制度は国内の物件のみ対象となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q33',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => 'LIXIL商品及び取付は社販制度を利用しますが、内装（クロス・フローリング）は知り合いの工務店で行いたいが可能ですか？',
                'ques_message'           => '原則は別リフォーム工事として受けることは可能ですが、他工事会社との調整が必要となりますので、現地担当者とご相談ください。なお、社販制度の見積については他業者への見積等の情報開示は禁止と致します。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q34',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => '以前（株）LIXILトータルサービスでリフォームを行いましたが、大変不満だったので、（株）LIXILトータルサービス以外でリフォームを行いたいのですが、可能でしょうか？',
                'ques_message'           => '今回（株）LIXILトータルサービスが工事対応窓口となっております。以前のご不満点をお聞かせ頂き、十分に留意した上で対応させていただきます。本制度はLIXIL Family STORE指定の工事業者のみの対応となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q35',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => '現住所と違う場所のリフォームを行いたいのですが、可能ですか？',
                'ques_message'           => '原則、現住所物件のリフォームとなります。
ファミリー会員の方は、現住所の住宅のみとなりますが、LIXIL会員の方で、引越予定先の自宅、本人所有の別荘や、単身赴任で本人所有の自宅に限り、可能です。申込み時に、リフォーム場所に、その旨チェックして申し込んで下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q36',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => 'LIXIL会員ですが、会員登録した住所と違う場所のリフォームを行いたいのですが、可能ですか？',
                'ques_message'           => '原則、会員登録した現住所物件のリフォームとなります。
但し、LIXIL会員の方で、引越予定先の自宅、本人所有の別荘や、単身赴任で本人所有の自宅に限り、可能です。
申込み時に、リフォーム場所に、その旨チェックして申し込んで下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q37',
                'syanaigai_kbn'          => '3',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => 'ファミリー会員ですが、会員登録した住所と違う場所のリフォームを行いたいのですが、可能ですか？',
                'ques_message'           => '申し訳ございません。会員登録された、現住所物件のみのリフォームとなります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q38',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => '申し込み後のリフォーム内容の打ち合わせは休日（土日）で依頼したいが対応可能ですか？',
                'ques_message'           => 'ショップでは土曜日も対応していますが、それ以外は別途ご相談となります。ショップ担当者にご相談下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q39',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => 'リフォーム工事を急いで行いたいのですが、対応していただけますか？',
                'ques_message'           => '出来る限り対応致しますが、ご要望に応えることが可能かは、（株）LIXILトータルサービスショプ営業部(lts10@lixil.com)にご相談下さい。お申し込み後は現地窓口にご確認ください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q40',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => 'リフォーム工事後、不具合はどのように対応してもらえますか？',
                'ques_message'           => '工事に関することは、LIXILトータルサービスの工事対応部門が、商品自体の不具合は、製造元であるLIXILが対応致します。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q41',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '工事・対応',
                'ask_message'            => '離島に住んでいます。対応頂けますか？',
                'ques_message'           => '基本対応可能ですが、対応不可の所もあります。可能か否かは（株）LIXILトータルサービスショプ営業部(lts10@lixil.com)にお問い合わせ下さい。尚、離島対応については別途経費が発生致しますことを御了承下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q42',
                'syanaigai_kbn'          => '4',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '商品・価格',
                'ask_message'            => 'LIXIL Family STORE リフォーム版の価格はどこを観たら分かりますか？',
                'ques_message'           => '参考金額として、LIXIL Family STOREの専用WEBサイトに掲載しております。詳細をご確認されたい場合は会員登録を実施いただき、ご確認ください。
※ 価格情報は他へ漏らさぬ様、徹底をお願い致します。本制度をご紹介するご家族の方も同様に価格情報を漏らさぬ様、徹底をお願い致します。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q43',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '商品・価格',
                'ask_message'            => 'LIXIL Family STORE リフォーム版の対象商品は何ですか？',
                'ques_message'           => 'LIXIL商品の良さを実感できる付加価値の高い、リフォームのお勧め商品が対象となります。詳細はLIXIL Family STORE 専用WEBサイト商品掲載ページでご確認下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q44',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '商品・価格',
                'ask_message'            => 'LIXIL Family STORE リフォーム版は商品のみ購入することは可能ですか？',
                'ques_message'           => '商品のみ購入する事は出来ません。
LIXIL Family STORE（リフォーム版）は商品と工事を併せてご提供する制度となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q45',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '請求・支払',
                'ask_message'            => 'LIXIL Family STORE リフォーム版はLIXIL無金利ローンの活用は可能ですか？',
                'ques_message'           => 'ローン適用条件に合致する場合はご利用になれます。
具体的には、リフォーム工事を担当するショップより、お見積もり提示後、担当者とご相談下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q46',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '請求・支払',
                'ask_message'            => 'LIXIL Family STORE リフォーム版の支払はカード払いで問題ないですか？',
                'ques_message'           => '現金での御振込みとなります。クレジットカードでの支払いは受付する事は出来ません。ご了承ください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q47',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '請求・支払',
                'ask_message'            => 'LIXIL Family STORE リフォーム版のリフォーム工事の支払はどの様にすれば良いですか？',
                'ques_message'           => '着工金がある場合を除き工事完了後の現金振り込みでのお支払いとなります。',
                'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q48',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '請求・支払',
                'ask_message'            => 'LIXIL Family STORE リフォーム版のリフォームの支払いは、給与や賞与等での天引きは可能ですか？（分割も含めて）',
                'ques_message'           => '申し訳ございません。給与や賞与での天引きにはたいおうしておりません。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q49',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '請求・支払',
                'ask_message'            => 'LIXIL Family STORE リフォーム版の支払方法にはどのような方法があるのですか？',
                'ques_message'           => '基本は、銀行からのお振込みになります。又、ローンでのお支払いも可能ですが、リフォーム工事を担当するショップより、お見積もり提示後、担当者とご相談下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q50',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => Carbon::parse('10/25/2017')->format('Y-m-d'),
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STORE リフォーム版の対象者は誰ですか？',
                'ques_message'           => 'LIXIL会員・・・LIXILグループ（㈱LIXILグループを含む、(株)LIXILグループ及び同社の子会社、関連会社において業務委託先であり、個人又は法人に属する社員であり、かつLIXILグループ（㈱LIXILグループを含む、(株)LIXILグループ及び同社の子会社、関連会社の事業所内に席を持ち、且つLIXILが認めた方となります。
ファミリー会員・・・LIXIL会員の家族。※ 上記以外の方が利用されていると確認が取れた場合には、従業員の方は厳しく罰せられる可能性があります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q51',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STORE リフォーム版のリフォーム工事の実施回数に限度はありますか？',
                'ques_message'           => 'リフォームでのご利用に関して、原則、回数制限は設けていませんが、同一部位同一商品リフォーム
 （同じ建物の同じ部分で同じ商品のリフォーム）の特別価格での対応は、年間１回を限度とさせていただきます。
又、ご利用回数が極端に多い場合、制限をさせていただく場合もありますので、ご了承願います。
',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q52',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STOREで、家族の招待件数に限度はありますか？',
                'ques_message'           => 'LIXIL会員として会員登録した従業員１人につき、年間５人まで家族の方を招待してファミリー会員として登録をすることが出来ます。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q53',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STORE リフォームストア制度を利用したいのですが、専用WEBサイト以外で、申し込みは可能ですか？',
                'ques_message'           => '不可です。専用WEBサイトのみになります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q54',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXILの他の割引制度とLIXIL Family STORE リフォーム版の割引制度の併用は可能ですか？',
                'ques_message'           => '申し訳ございません。原則、他の割引制度との併用は出来ません。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q55',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '該当商品のリフォーム工事以外に、同時に他のリフォーム工事も依頼したいのですが対応可能ですか？',
                'ques_message'           => 'お考えいただいているリフォーム工事を伺った上で、ご対応させて頂きます。（内容によってはご対応できない場合もございます。）ご連絡差し上げるショップ担当にご相談下さい。尚、LIXIL Family STORE 対象以外の商品は通常価格となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q56',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '大切な家族とはどの範囲となるのですか。',
                'ques_message'           => 'LIXIL会員となる権利がある方のご家族が「大切な家族の範囲」となります。知人・友人は含まれません。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q57',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STORE制度の問合せはどこですか？',
                'ques_message'           => 'LIXIL Family STORE事務局になります。
（lffs@lixil.com）へメールでお問い合わせ下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q58',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '現在、家族帯同で転勤しております。自分が名義主となっている別住所の建物のリフォーム工事は対応してももらえますか？',
                'ques_message'           => '名義主様でしたら、対応する事ができます。但し、必ずリフォーム工事日を含めて、現地での立ち合いをしてください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q59',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '自分は賃貸物件に住んでいますが、この制度は賃貸物件でも活用できますか？オーナーには了解を取っています。',
                'ques_message'           => '申し訳ございません。ご自身の名義ではない賃貸物件は対象外となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q60',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '自分はLIXIL会員として登録をしていますが、
LIXIL会員として、自分の両親の名義となっている家のリフォーム工事をしたいと考えております。LIXIL Family STORE リフォーム版についてLIXIL会員として申し込むことは可能ですか？',
                'ques_message'           => '申し訳ございません。LIXIL Family STORE リフォーム版はリフォーム工事の対象となる建物の名義主の方がお申し込みをしていただく規約となっております。恐れ入りますが、ご両親様をファミリー会員としてご招待をしていただき、制度を利用をしてください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q61',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '現在、LIXIL商品を使用して、リフォーム工事を検討しています。同じ商品の見積を他社と比較して、見積を取得しても良いですか？',
                'ques_message'           => '原則、他社との比較をしていただいての相見積の行為は禁止とさせていただきます。尚、万が一他社でもリフォーム工事を検討されていた場合において、該当となるリフォーム工事をお断りする際は、本制度の内容は一切公表せずに、お断りをいただけますようお願い致します。LIXIL Family STORE リフォーム版の対象となる方を除いて、社外への情報開示は一切厳禁と致します。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q62',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'あるリフォーム業者にLIXIL商品を使ったリフォームをお願いしています。リフォーム工事の契約は済んでおりますが、支払前なのですが、LIXIL Family STORE リフォーム版で値引きをしていただくことは可能ですか？',
                'ques_message'           => '申し訳ございません。LIXIL Family STORE リフォーム版として対応する事は出来ません。専用WEBサイトでのお申込みに限り利用できる制度です。又、契約後の案件には対応できませんのでご了承下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q63',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STORE リフォーム版は自分が所有している別荘は対象となりますか？',
                'ques_message'           => 'LIXIL会員の方は自己の保養目的であり、且つLIXIL会員名義の別荘は対象となります。但し、必ず工事日は立ち合いをしてください。尚、ファミリー会員の方はファミリー会員自身の名義となっている別荘であっても対象外とさせていただきます。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q64',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '私はLIXILグループの派遣社員（業務委託社員）ですが、LIXIL Family STORE リフォーム版の制度利用できますか？',
                'ques_message'           => 'LIXIL Family STORE リフォーム版をご利用可能です。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q65',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => Carbon::parse('10/25/2017')->format('Y-m-d'),
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '私は会社でPCを貸与されていません。どの様に申込すれば良いのですか？',
                'ques_message'           => '共有のパソコンを利用しても、LIXIL Family STORE リフォーム版を利用することは可能です。但し、LIXILグループのメールアドレスをお持ちでは無い方は、恐れ入りますが、原則としてメールアドレスの取得を実施いただけますよう、お願い致します。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q66',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '私は会社でPCを貸与されていません。どの様に申込すれば良いのですか？',
                'ques_message'           => '共有のパソコン等で、LIXIL社内イントラのLIXIL Family STORE 紹介ページで、会員登録方法を確認いただいた上で、LIXIL会員として会員登録して下さい。LIXIL会員登録後は、自宅PCでも、ログインしてご利用できます。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q67',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '現在、（株）LIXILビバが運用しているLIXILグループのメンバー割引との併用は可能ですか？',
                'ques_message'           => '申し訳ございません。他の割引制度との併用は出来ません。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q68',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => Carbon::parse('10/25/2017')->format('Y-m-d'),
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '住宅ストック補助金の申請も合わせてできますか？',
                'ques_message'           => '2017年9月7日が公布申請の最終締め切り日です。それ以降は対象外となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q69',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '3',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STORE 住宅購入･紹介制度の対象者は誰ですか？',
                'ques_message'           => '当面は、(株)LIXILの役員、従業員 となります。
追って、(株)LIXILグループ、の役員、従業員(株)LIXILおよびLIXILグループの子会社、関連会社の役員、従業員等も対象としていく予定です。
但し、役員の方は、家族、友人・知人の紹介は可能ですが、本人の住宅購入は対象外となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q70',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '3',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STORE 住宅購入･紹介制度を家族・知人が活用する事は可能ですか？',
                'ques_message'           => '住宅購入･紹介制度は、LIXIL会員のみ活用可能です。
但し、LIXIL会員が、家族、知人、友人の案件として紹介することは可能です。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q71',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STOREの会員有効期限はありますか？',
                'ques_message'           => '会員有効期限はありません。
但し、LIXILグループを退職等で従業員ではなくなった方は、退会となります。また、退会されたLIXIL会員より紹介を受けたファミリー会員の方も同様に退会となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q72',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STORE リフォームと住宅購入・紹介を併用して制度を活用する事は可能ですか？',
                'ques_message'           => 'LIXIL Family STORE リフォームと新築紹介は、併用して制度を活用する事は出来ません。各々別制度として利用可能ですので、それぞれでお申し込み下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q73',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STOREを家族が利用したいのですが、どうしたらよいですか？',
                'ques_message'           => 'LIXILグループ従業員の方がLIXIL Family STORE LIXIL会員として会員登録まで完了をしていただき、その後、ご家族を招待してください。招待されたご家族は、LIXIL Family STORE ファミリー会員として会員登録を実施してください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q74',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '今、グループ会社（ビバ・（株）LIXILトータルサービス等）でリフォームの見積しています。この制度への切替は可能ですか？',
                'ques_message'           => '原則、LIXILグループ会社であっても他社様との商談進行中の案件に対して、切り替えは対応できません。他社様との商談をお断りいただいた上での対応とさせていただきます。但し、（株）LIXILトータルサービス（直営ショップ含む）の場合、商談中の（株）LIXILトータルサービス担当と相談の上、LIXIL Family STORE サイトにて申込かつ、工期の変更等を御了承いただければ、切替可能とさせていただきます。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q75',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '現在会社として社員販売の購入ルール（特典）がありますが、併用可能ですか？',
                'ques_message'           => '申し訳ございません、原則併用は出来ません。ご了承ください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q76',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '1',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'この制度は何回も利用できるのですか？',
                'ques_message'           => '原則、何回でも利用可能です。但し、極端な回数が確認された場合は、制限をさせて頂く場合もあります。
尚、リフォーム版でのご利用に関しても、原則、回数制限は設けていませんが、同一部位同一商品リフォーム
 （同じ建物の同じ部分で同じ商品のリフォーム）の特別価格での対応は、年間１回を限度とさせていただきます。
',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q77',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '3',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '住宅購入・紹介制度と、LIXIL新築キャッシュバック制度を併用することは可能ですか？',
                'ques_message'           => 'その他のキャッシュバックキャンペーン等との併用は出来ません。※詳細は、該当する他のキャンペーンの規約に準じて下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q78',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '3',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '新築紹介で、本制度とは別に、既に各ハウスメーカー若しくはデベロッパーと契約に関する交渉を始めていますが、本制度を活用して、紹介を受ける事は可能ですか？',
                'ques_message'           => '交渉進行中の案件は申し込み出来ません。
住宅購入･紹介の制度を活用できるのは、各社展示場等で名簿記載や折衝をしていない案件に限られています。
交渉中の案件の場合、ハウスメーカー若しくはデベロッパーとトラブルの原因となりますので、対象外とさせていただきます。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q79',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '新築を検討しています。その新築にLIXIL Family STORE リフォーム制度を利用して社販対応商品を使いたいのですが可能ですか？',
                'ques_message'           => '新築案件での対応は出来ません。社販対象商品は、リフォームのみの対応となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q80',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '制度利用にあたり禁止事項や注意事項はありますか？',
                'ques_message'           => 'LIXIL Family STORE リフォームストアではLIXIL商品を使ったリフォームを特別価格でご提供しております。制度で取得した情報をLIXILの取引先、得意先および第三者に対して、公開することを禁止事項と致します。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q81',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '先日、グループ会社（ビバ・（株）LIXILトータルサービス等）で契約してしまいました。まだ着工前なので制度への切替をしたいが可能ですか？又、窓口から説得頂けますか？',
                'ques_message'           => '申し訳ございません、既に契約済みの案件は対象外となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q82',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '賃貸物件を所有しているのですが、社販制度でリフォームを行うことは可能ですか？',
                'ques_message'           => '賃貸物件は対象外となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q83',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '持家に現在住んでおらず人に貸しています。退去時のリフォームに、この制度を都度活用しても良いでしょうか？',
                'ques_message'           => 'LIXIL Family STORE LIXIL会員（申込みする本人）所有の物件であれば、リフォーム制度の対象となります。但し、本人所有の確認をさせていただきます。原則、本人の立会をしていただきます。尚、ファミリー会員の方は、会員登録いただいた現住所のみ対象となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q84',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'ユーザーアンケートや施工事例写真などの協力事項はあるのですか？',
                'ques_message'           => 'ユーザーアンケートや施工事例写真などの協力をお願いすることがあります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q85',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '3',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '私の知り合いが新築を検討しようとしています。LIXIL  Family STORE の住宅購入･紹介制度を利用することは可能ですか？',
                'ques_message'           => 'LIXIL会員で住宅購入･紹介制度を利用出来る方であれば、家族、知人、友人の案件として紹介することができます。その場合は『住宅購入祝い一時金』を受け取ることはできませんが、被紹介者専用『商品ポイントキャッシュバック』を受け取る事が出来ます。更に、各ハウスメーカー、デベロッパーが設定している紹介特典も同時に適用される場合もあります。※詳細は、特典一覧をご確認ください。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q86',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '私の知り合いがLIXIL社販対象商品を使ったリフォームを検討中です。LIXIL従業員が申し込めば、紹介して社販制度を利用させることは可能でしょうか。',
                'ques_message'           => '申し訳ございません。知人、友人の方は対象外となります。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q87',
                'syanaigai_kbn'          => '2',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '現在、両親の名義となっている実家のリフォームを検討しております。自分はLIXIL会員として会員登録をし、LIXIL Family STORE リフォームストアで申し込みをします。リフォームに掛かる費用は両親へのプレゼントとして、LIXIL会員である自分が支払います。本制度は活用出来ますか？',
                'ques_message'           => '申し訳ございません。LIXIL Family STORE リフォームストアはお申し込みをいただいた会員方自身の名義（共同名義含む）でない場合、利用出来ません。ご両親を招待して、ファミリー会員に会員登録いただいた上で、ご両親にご利用いただいて下さい。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q88',
                'syanaigai_kbn'          => '1',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('08/31/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '商品・価格',
                'ask_message'            => 'LIXIL Family STORE リフォームストアで対象となっている商品以外を特別に対象商品にしていただき、LIXIL Family STORE リフォームストアとしてもらう事は可能ですか。',
                'ques_message'           => 'LIXIL Family STORE リフォームストアの対象商品として定めている以外の商品は、LIXIL Family STORE リフォームストア対象外となります。従ってLIXIL Family STORE リフォームストアと同じ条件条件にはできません。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q89',
                'syanaigai_kbn'          => '4',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => 'LIXIL Family STORE リフォームストアで対象商品のシリーズの中で、キッチン本体を除く、吊戸棚やゴミ箱のみを購入したいと考えています。リフォームストアで購入することは可能でしょうか。',
                'ques_message'           => '申し訳ございません。対象商品であった場合でも、本体を除く付属品となる商品のみの購入は出来ません。',
                  'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],
            [
                'faskq_id'               => 'q90',
                'syanaigai_kbn'          => '4',
                'faq_taisyou_kbn'        => '2',
                'faq_start_ymd'          => Carbon::parse('10/26/2017')->format('Y-m-d'),
                'faq_end_ymd'            => null,
                'ask_bunrui'             => '制度・申込み',
                'ask_message'            => '現在、家のレンジフードが故障しており、レンジフードのみの交換を考えています。LIXIL Family STORE リフォームストアで対象商品のシリーズの中で、レンジフードのみを選択して購入したいのですが、リフォームストアで購入することは可能でしょうか。',
                'ques_message'           => '申し訳ございません。対象商品であった場合でも、本体を除く付属品となる商品のみの購入は出来ません。',
                 'regis_date'             => Carbon::now(),
                'regis_user_acct_cd'     => 'abc123',
                'regis_terminal_ip_addr' => '1',
                'upd_pgm_cd'             => '1',
                'upd_date'               => Carbon::now(),
                'patch_id'               => '1',
                
            ],

            
        ];


        DB::beginTransaction();
        try {

            foreach( $faqs as $key => $faq) {

                $faqDB = Faq::find($faq['faskq_id']);

                if($faqDB) {

					$faqDB ->syanaigai_kbn          = $faq['syanaigai_kbn'];
					$faqDB ->faq_taisyou_kbn        = $faq['faq_taisyou_kbn'];
					$faqDB ->faq_start_ymd          = $faq['faq_start_ymd'];
					$faqDB ->faq_end_ymd            = $faq['faq_end_ymd'];
					$faqDB ->ask_bunrui             = $faq['ask_bunrui'];
					$faqDB ->ask_message            = $faq['ask_message'];
					$faqDB ->ques_message           = $faq['ques_message'];
					$faqDB ->regis_date             = $faq['regis_date'];
					$faqDB ->regis_user_acct_cd     = $faq['regis_user_acct_cd'];
					$faqDB ->regis_terminal_ip_addr = $faq['regis_terminal_ip_addr'];
					$faqDB ->upd_pgm_cd             = $faq['upd_pgm_cd'];
					$faqDB ->upd_date               = $faq['upd_date'];
					$faqDB ->patch_id               = $faq['patch_id'];

					$faqDB -> save();
                }
            }
                
            $this->insertSeeder();
            DB::commit();

        } catch (\Exception $ex) {
            DB::rollback();
            throw $ex;
        }

    }
}
